// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.github.amapkit.location

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LocationMessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class NativeLocationAccuracy(val raw: Int) {
  HIGH(0),
  BALANCED(1),
  LOW_POWER(2);

  companion object {
    fun ofRaw(raw: Int): NativeLocationAccuracy? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeAndroidLocationMode(val raw: Int) {
  HIGH_ACCURACY(0),
  BATTERY_SAVING(1),
  DEVICE_SENSORS(2);

  companion object {
    fun ofRaw(raw: Int): NativeAndroidLocationMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeAndroidLocationProtocol(val raw: Int) {
  HTTP(0),
  HTTPS(1);

  companion object {
    fun ofRaw(raw: Int): NativeAndroidLocationProtocol? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeAndroidLocationPurpose(val raw: Int) {
  SIGN_IN(0),
  TRANSPORT(1),
  SPORT(2);

  companion object {
    fun ofRaw(raw: Int): NativeAndroidLocationPurpose? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeAndroidGeoLanguage(val raw: Int) {
  SYSTEM(0),
  CHINESE(1),
  ENGLISH(2);

  companion object {
    fun ofRaw(raw: Int): NativeAndroidGeoLanguage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeCoordinateType(val raw: Int) {
  GCJ02(0),
  WGS84(1),
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): NativeCoordinateType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeLocationErrorCode(val raw: Int) {
  PRIVACY_NOT_CONFIGURED(0),
  API_KEY_MISSING(1),
  PERMISSION_NOT_DETERMINED(2),
  PERMISSION_DENIED(3),
  PERMISSION_DENIED_FOREVER(4),
  PERMISSION_RESTRICTED(5),
  SERVICE_DISABLED(6),
  TIMEOUT(7),
  SDK_INITIALIZATION_FAILED(8),
  BACKGROUND_UNSUPPORTED(9),
  OPERATION_IN_PROGRESS(10),
  CLIENT_NOT_FOUND(11),
  UNSUPPORTED(12),
  UNKNOWN(13);

  companion object {
    fun ofRaw(raw: Int): NativeLocationErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativePrivacyStatus (
  val privacyNoticeShown: Boolean,
  val containsAmapPrivacyPolicy: Boolean,
  val userAgreed: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativePrivacyStatus {
      val privacyNoticeShown = pigeonVar_list[0] as Boolean
      val containsAmapPrivacyPolicy = pigeonVar_list[1] as Boolean
      val userAgreed = pigeonVar_list[2] as Boolean
      return NativePrivacyStatus(privacyNoticeShown, containsAmapPrivacyPolicy, userAgreed)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      privacyNoticeShown,
      containsAmapPrivacyPolicy,
      userAgreed,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativePrivacyStatus
    return LocationMessagesPigeonUtils.deepEquals(this.privacyNoticeShown, other.privacyNoticeShown) && LocationMessagesPigeonUtils.deepEquals(this.containsAmapPrivacyPolicy, other.containsAmapPrivacyPolicy) && LocationMessagesPigeonUtils.deepEquals(this.userAgreed, other.userAgreed)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.privacyNoticeShown)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.containsAmapPrivacyPolicy)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.userAgreed)
    return result
  }
  override fun toString(): String {
    return "NativePrivacyStatus(privacyNoticeShown=$privacyNoticeShown, containsAmapPrivacyPolicy=$containsAmapPrivacyPolicy, userAgreed=$userAgreed)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeLocationOptions (
  val accuracy: NativeLocationAccuracy,
  val intervalMillis: Long,
  val timeoutMillis: Long,
  val needAddress: Boolean,
  val android: NativeAndroidLocationOptions? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeLocationOptions {
      val accuracy = pigeonVar_list[0] as NativeLocationAccuracy
      val intervalMillis = pigeonVar_list[1] as Long
      val timeoutMillis = pigeonVar_list[2] as Long
      val needAddress = pigeonVar_list[3] as Boolean
      val android = pigeonVar_list[4] as NativeAndroidLocationOptions?
      return NativeLocationOptions(accuracy, intervalMillis, timeoutMillis, needAddress, android)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accuracy,
      intervalMillis,
      timeoutMillis,
      needAddress,
      android,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeLocationOptions
    return LocationMessagesPigeonUtils.deepEquals(this.accuracy, other.accuracy) && LocationMessagesPigeonUtils.deepEquals(this.intervalMillis, other.intervalMillis) && LocationMessagesPigeonUtils.deepEquals(this.timeoutMillis, other.timeoutMillis) && LocationMessagesPigeonUtils.deepEquals(this.needAddress, other.needAddress) && LocationMessagesPigeonUtils.deepEquals(this.android, other.android)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.accuracy)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.intervalMillis)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.timeoutMillis)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.needAddress)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.android)
    return result
  }
  override fun toString(): String {
    return "NativeLocationOptions(accuracy=$accuracy, intervalMillis=$intervalMillis, timeoutMillis=$timeoutMillis, needAddress=$needAddress, android=$android)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAndroidLocationOptions (
  val locationMode: NativeAndroidLocationMode? = null,
  val locationProtocol: NativeAndroidLocationProtocol,
  val httpTimeoutMillis: Long,
  val mockEnabled: Boolean,
  val needAddress: Boolean,
  val wifiScanEnabled: Boolean,
  val alwaysScanWifi: Boolean,
  val locationCacheEnabled: Boolean,
  val onceLocationLatest: Boolean,
  val sensorEnabled: Boolean,
  val gpsFirst: Boolean,
  val gpsFirstTimeoutMillis: Long,
  val beidouFirst: Boolean,
  val deviceModeDistanceFilterMeters: Double,
  val geoLanguage: NativeAndroidGeoLanguage,
  val locationPurpose: NativeAndroidLocationPurpose? = null,
  val coordinateOffsetEnabled: Boolean,
  val selfStartServiceEnabled: Boolean,
  val killProcessOnDestroy: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAndroidLocationOptions {
      val locationMode = pigeonVar_list[0] as NativeAndroidLocationMode?
      val locationProtocol = pigeonVar_list[1] as NativeAndroidLocationProtocol
      val httpTimeoutMillis = pigeonVar_list[2] as Long
      val mockEnabled = pigeonVar_list[3] as Boolean
      val needAddress = pigeonVar_list[4] as Boolean
      val wifiScanEnabled = pigeonVar_list[5] as Boolean
      val alwaysScanWifi = pigeonVar_list[6] as Boolean
      val locationCacheEnabled = pigeonVar_list[7] as Boolean
      val onceLocationLatest = pigeonVar_list[8] as Boolean
      val sensorEnabled = pigeonVar_list[9] as Boolean
      val gpsFirst = pigeonVar_list[10] as Boolean
      val gpsFirstTimeoutMillis = pigeonVar_list[11] as Long
      val beidouFirst = pigeonVar_list[12] as Boolean
      val deviceModeDistanceFilterMeters = pigeonVar_list[13] as Double
      val geoLanguage = pigeonVar_list[14] as NativeAndroidGeoLanguage
      val locationPurpose = pigeonVar_list[15] as NativeAndroidLocationPurpose?
      val coordinateOffsetEnabled = pigeonVar_list[16] as Boolean
      val selfStartServiceEnabled = pigeonVar_list[17] as Boolean
      val killProcessOnDestroy = pigeonVar_list[18] as Boolean
      return NativeAndroidLocationOptions(locationMode, locationProtocol, httpTimeoutMillis, mockEnabled, needAddress, wifiScanEnabled, alwaysScanWifi, locationCacheEnabled, onceLocationLatest, sensorEnabled, gpsFirst, gpsFirstTimeoutMillis, beidouFirst, deviceModeDistanceFilterMeters, geoLanguage, locationPurpose, coordinateOffsetEnabled, selfStartServiceEnabled, killProcessOnDestroy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      locationMode,
      locationProtocol,
      httpTimeoutMillis,
      mockEnabled,
      needAddress,
      wifiScanEnabled,
      alwaysScanWifi,
      locationCacheEnabled,
      onceLocationLatest,
      sensorEnabled,
      gpsFirst,
      gpsFirstTimeoutMillis,
      beidouFirst,
      deviceModeDistanceFilterMeters,
      geoLanguage,
      locationPurpose,
      coordinateOffsetEnabled,
      selfStartServiceEnabled,
      killProcessOnDestroy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAndroidLocationOptions
    return LocationMessagesPigeonUtils.deepEquals(this.locationMode, other.locationMode) && LocationMessagesPigeonUtils.deepEquals(this.locationProtocol, other.locationProtocol) && LocationMessagesPigeonUtils.deepEquals(this.httpTimeoutMillis, other.httpTimeoutMillis) && LocationMessagesPigeonUtils.deepEquals(this.mockEnabled, other.mockEnabled) && LocationMessagesPigeonUtils.deepEquals(this.needAddress, other.needAddress) && LocationMessagesPigeonUtils.deepEquals(this.wifiScanEnabled, other.wifiScanEnabled) && LocationMessagesPigeonUtils.deepEquals(this.alwaysScanWifi, other.alwaysScanWifi) && LocationMessagesPigeonUtils.deepEquals(this.locationCacheEnabled, other.locationCacheEnabled) && LocationMessagesPigeonUtils.deepEquals(this.onceLocationLatest, other.onceLocationLatest) && LocationMessagesPigeonUtils.deepEquals(this.sensorEnabled, other.sensorEnabled) && LocationMessagesPigeonUtils.deepEquals(this.gpsFirst, other.gpsFirst) && LocationMessagesPigeonUtils.deepEquals(this.gpsFirstTimeoutMillis, other.gpsFirstTimeoutMillis) && LocationMessagesPigeonUtils.deepEquals(this.beidouFirst, other.beidouFirst) && LocationMessagesPigeonUtils.deepEquals(this.deviceModeDistanceFilterMeters, other.deviceModeDistanceFilterMeters) && LocationMessagesPigeonUtils.deepEquals(this.geoLanguage, other.geoLanguage) && LocationMessagesPigeonUtils.deepEquals(this.locationPurpose, other.locationPurpose) && LocationMessagesPigeonUtils.deepEquals(this.coordinateOffsetEnabled, other.coordinateOffsetEnabled) && LocationMessagesPigeonUtils.deepEquals(this.selfStartServiceEnabled, other.selfStartServiceEnabled) && LocationMessagesPigeonUtils.deepEquals(this.killProcessOnDestroy, other.killProcessOnDestroy)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.locationMode)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.locationProtocol)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.httpTimeoutMillis)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.mockEnabled)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.needAddress)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.wifiScanEnabled)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.alwaysScanWifi)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.locationCacheEnabled)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.onceLocationLatest)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.sensorEnabled)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.gpsFirst)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.gpsFirstTimeoutMillis)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.beidouFirst)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.deviceModeDistanceFilterMeters)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.geoLanguage)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.locationPurpose)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.coordinateOffsetEnabled)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.selfStartServiceEnabled)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.killProcessOnDestroy)
    return result
  }
  override fun toString(): String {
    return "NativeAndroidLocationOptions(locationMode=$locationMode, locationProtocol=$locationProtocol, httpTimeoutMillis=$httpTimeoutMillis, mockEnabled=$mockEnabled, needAddress=$needAddress, wifiScanEnabled=$wifiScanEnabled, alwaysScanWifi=$alwaysScanWifi, locationCacheEnabled=$locationCacheEnabled, onceLocationLatest=$onceLocationLatest, sensorEnabled=$sensorEnabled, gpsFirst=$gpsFirst, gpsFirstTimeoutMillis=$gpsFirstTimeoutMillis, beidouFirst=$beidouFirst, deviceModeDistanceFilterMeters=$deviceModeDistanceFilterMeters, geoLanguage=$geoLanguage, locationPurpose=$locationPurpose, coordinateOffsetEnabled=$coordinateOffsetEnabled, selfStartServiceEnabled=$selfStartServiceEnabled, killProcessOnDestroy=$killProcessOnDestroy)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeLocation (
  val latitude: Double,
  val longitude: Double,
  val accuracyMeters: Double,
  val timestampMillis: Long,
  val coordinateType: NativeCoordinateType,
  val address: NativeLocationAddress? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeLocation {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      val accuracyMeters = pigeonVar_list[2] as Double
      val timestampMillis = pigeonVar_list[3] as Long
      val coordinateType = pigeonVar_list[4] as NativeCoordinateType
      val address = pigeonVar_list[5] as NativeLocationAddress?
      return NativeLocation(latitude, longitude, accuracyMeters, timestampMillis, coordinateType, address)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
      accuracyMeters,
      timestampMillis,
      coordinateType,
      address,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeLocation
    return LocationMessagesPigeonUtils.deepEquals(this.latitude, other.latitude) && LocationMessagesPigeonUtils.deepEquals(this.longitude, other.longitude) && LocationMessagesPigeonUtils.deepEquals(this.accuracyMeters, other.accuracyMeters) && LocationMessagesPigeonUtils.deepEquals(this.timestampMillis, other.timestampMillis) && LocationMessagesPigeonUtils.deepEquals(this.coordinateType, other.coordinateType) && LocationMessagesPigeonUtils.deepEquals(this.address, other.address)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.latitude)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.longitude)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.accuracyMeters)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.timestampMillis)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.coordinateType)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.address)
    return result
  }
  override fun toString(): String {
    return "NativeLocation(latitude=$latitude, longitude=$longitude, accuracyMeters=$accuracyMeters, timestampMillis=$timestampMillis, coordinateType=$coordinateType, address=$address)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeLocationAddress (
  val formattedAddress: String? = null,
  val country: String? = null,
  val province: String? = null,
  val city: String? = null,
  val district: String? = null,
  val cityCode: String? = null,
  val adCode: String? = null,
  val street: String? = null,
  val streetNumber: String? = null,
  val poiName: String? = null,
  val aoiName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeLocationAddress {
      val formattedAddress = pigeonVar_list[0] as String?
      val country = pigeonVar_list[1] as String?
      val province = pigeonVar_list[2] as String?
      val city = pigeonVar_list[3] as String?
      val district = pigeonVar_list[4] as String?
      val cityCode = pigeonVar_list[5] as String?
      val adCode = pigeonVar_list[6] as String?
      val street = pigeonVar_list[7] as String?
      val streetNumber = pigeonVar_list[8] as String?
      val poiName = pigeonVar_list[9] as String?
      val aoiName = pigeonVar_list[10] as String?
      return NativeLocationAddress(formattedAddress, country, province, city, district, cityCode, adCode, street, streetNumber, poiName, aoiName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      formattedAddress,
      country,
      province,
      city,
      district,
      cityCode,
      adCode,
      street,
      streetNumber,
      poiName,
      aoiName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeLocationAddress
    return LocationMessagesPigeonUtils.deepEquals(this.formattedAddress, other.formattedAddress) && LocationMessagesPigeonUtils.deepEquals(this.country, other.country) && LocationMessagesPigeonUtils.deepEquals(this.province, other.province) && LocationMessagesPigeonUtils.deepEquals(this.city, other.city) && LocationMessagesPigeonUtils.deepEquals(this.district, other.district) && LocationMessagesPigeonUtils.deepEquals(this.cityCode, other.cityCode) && LocationMessagesPigeonUtils.deepEquals(this.adCode, other.adCode) && LocationMessagesPigeonUtils.deepEquals(this.street, other.street) && LocationMessagesPigeonUtils.deepEquals(this.streetNumber, other.streetNumber) && LocationMessagesPigeonUtils.deepEquals(this.poiName, other.poiName) && LocationMessagesPigeonUtils.deepEquals(this.aoiName, other.aoiName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.formattedAddress)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.country)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.province)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.city)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.district)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.cityCode)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.adCode)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.street)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.streetNumber)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.poiName)
    result = 31 * result + LocationMessagesPigeonUtils.deepHash(this.aoiName)
    return result
  }
  override fun toString(): String {
    return "NativeLocationAddress(formattedAddress=$formattedAddress, country=$country, province=$province, city=$city, district=$district, cityCode=$cityCode, adCode=$adCode, street=$street, streetNumber=$streetNumber, poiName=$poiName, aoiName=$aoiName)"
  }
}
private open class LocationMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeLocationAccuracy.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeAndroidLocationMode.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeAndroidLocationProtocol.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeAndroidLocationPurpose.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeAndroidGeoLanguage.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeCoordinateType.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeLocationErrorCode.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativePrivacyStatus.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeLocationOptions.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAndroidLocationOptions.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeLocation.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeLocationAddress.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeLocationAccuracy -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NativeAndroidLocationMode -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is NativeAndroidLocationProtocol -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is NativeAndroidLocationPurpose -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is NativeAndroidGeoLanguage -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is NativeCoordinateType -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is NativeLocationErrorCode -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is NativePrivacyStatus -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is NativeLocationOptions -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is NativeAndroidLocationOptions -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is NativeLocation -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is NativeLocationAddress -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LocationHostApi {
  fun setApiKey(apiKey: String)
  fun setPrivacyStatus(status: NativePrivacyStatus)
  fun isLocationServiceEnabled(): Boolean
  fun createClient(options: NativeLocationOptions): Long
  fun setLocationOption(clientId: Long, options: NativeLocationOptions)
  fun getCurrentLocation(clientId: Long, callback: (Result<NativeLocation>) -> Unit)
  fun start(clientId: Long)
  fun stop(clientId: Long)
  fun disposeClient(clientId: Long)

  companion object {
    /** The codec used by LocationHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      LocationMessagesPigeonCodec()
    }
    /** Sets up an instance of `LocationHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LocationHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_kit_location_android.LocationHostApi.setApiKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val apiKeyArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setApiKey(apiKeyArg)
              listOf(null)
            } catch (exception: Throwable) {
              LocationMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_kit_location_android.LocationHostApi.setPrivacyStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val statusArg = args[0] as NativePrivacyStatus
            val wrapped: List<Any?> = try {
              api.setPrivacyStatus(statusArg)
              listOf(null)
            } catch (exception: Throwable) {
              LocationMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_kit_location_android.LocationHostApi.isLocationServiceEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isLocationServiceEnabled())
            } catch (exception: Throwable) {
              LocationMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_kit_location_android.LocationHostApi.createClient$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as NativeLocationOptions
            val wrapped: List<Any?> = try {
              listOf(api.createClient(optionsArg))
            } catch (exception: Throwable) {
              LocationMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_kit_location_android.LocationHostApi.setLocationOption$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            val optionsArg = args[1] as NativeLocationOptions
            val wrapped: List<Any?> = try {
              api.setLocationOption(clientIdArg, optionsArg)
              listOf(null)
            } catch (exception: Throwable) {
              LocationMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_kit_location_android.LocationHostApi.getCurrentLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            api.getCurrentLocation(clientIdArg) { result: Result<NativeLocation> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LocationMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LocationMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_kit_location_android.LocationHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.start(clientIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              LocationMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_kit_location_android.LocationHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.stop(clientIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              LocationMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.amap_kit_location_android.LocationHostApi.disposeClient$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.disposeClient(clientIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              LocationMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class LocationFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LocationFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      LocationMessagesPigeonCodec()
    }
  }
  fun onLocation(clientIdArg: Long, locationArg: NativeLocation, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.amap_kit_location_android.LocationFlutterApi.onLocation$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(clientIdArg, locationArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LocationMessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onError(clientIdArg: Long, codeArg: NativeLocationErrorCode, messageArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.amap_kit_location_android.LocationFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(clientIdArg, codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LocationMessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
