name: amap_kit_map_example
description: Demonstrates amap_kit_map.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

resolution: workspace

dependencies:
  amap_kit_map:
    path: ..
  amap_kit_map_platform_interface: ^0.1.0
  flutter:
    sdk: flutter
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  permission_handler_platform_interface: ^4.3.0

flutter:
  uses-material-design: true
  assets:
    - ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
