// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum LocationMessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum NativeLocationAccuracy: Int, CaseIterable {
  case high = 0
  case balanced = 1
  case lowPower = 2
}

enum NativeIosDesiredAccuracy: Int, CaseIterable {
  case bestForNavigation = 0
  case best = 1
  case nearestTenMeters = 2
  case hundredMeters = 3
  case kilometer = 4
  case threeKilometers = 5
}

enum NativeIosAccuracyMode: Int, CaseIterable {
  case fullAndReduced = 0
  case full = 1
  case reduced = 2
}

enum NativeCoordinateType: Int, CaseIterable {
  case gcj02 = 0
  case wgs84 = 1
  case unknown = 2
}

enum NativeLocationErrorCode: Int, CaseIterable {
  case privacyNotConfigured = 0
  case apiKeyMissing = 1
  case permissionNotDetermined = 2
  case permissionDenied = 3
  case permissionDeniedForever = 4
  case permissionRestricted = 5
  case serviceDisabled = 6
  case timeout = 7
  case sdkInitializationFailed = 8
  case backgroundUnsupported = 9
  case operationInProgress = 10
  case clientNotFound = 11
  case unsupported = 12
  case unknown = 13
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativePrivacyStatus: Hashable, CustomStringConvertible {
  var privacyNoticeShown: Bool
  var containsAmapPrivacyPolicy: Bool
  var userAgreed: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePrivacyStatus? {
    let privacyNoticeShown = pigeonVar_list[0] as! Bool
    let containsAmapPrivacyPolicy = pigeonVar_list[1] as! Bool
    let userAgreed = pigeonVar_list[2] as! Bool

    return NativePrivacyStatus(
      privacyNoticeShown: privacyNoticeShown,
      containsAmapPrivacyPolicy: containsAmapPrivacyPolicy,
      userAgreed: userAgreed
    )
  }
  func toList() -> [Any?] {
    return [
      privacyNoticeShown,
      containsAmapPrivacyPolicy,
      userAgreed,
    ]
  }
  static func == (lhs: NativePrivacyStatus, rhs: NativePrivacyStatus) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LocationMessagesPigeonInternal.deepEquals(lhs.privacyNoticeShown, rhs.privacyNoticeShown) && LocationMessagesPigeonInternal.deepEquals(lhs.containsAmapPrivacyPolicy, rhs.containsAmapPrivacyPolicy) && LocationMessagesPigeonInternal.deepEquals(lhs.userAgreed, rhs.userAgreed)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativePrivacyStatus")
    LocationMessagesPigeonInternal.deepHash(value: privacyNoticeShown, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: containsAmapPrivacyPolicy, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: userAgreed, hasher: &hasher)
  }

  public var description: String {
    return "NativePrivacyStatus(privacyNoticeShown: \(String(describing: privacyNoticeShown)), containsAmapPrivacyPolicy: \(String(describing: containsAmapPrivacyPolicy)), userAgreed: \(String(describing: userAgreed)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeLocationOptions: Hashable, CustomStringConvertible {
  var accuracy: NativeLocationAccuracy
  var intervalMillis: Int64
  var timeoutMillis: Int64
  var needAddress: Bool
  var ios: NativeIosLocationOptions? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeLocationOptions? {
    let accuracy = pigeonVar_list[0] as! NativeLocationAccuracy
    let intervalMillis = pigeonVar_list[1] as! Int64
    let timeoutMillis = pigeonVar_list[2] as! Int64
    let needAddress = pigeonVar_list[3] as! Bool
    let ios: NativeIosLocationOptions? = nilOrValue(pigeonVar_list[4])

    return NativeLocationOptions(
      accuracy: accuracy,
      intervalMillis: intervalMillis,
      timeoutMillis: timeoutMillis,
      needAddress: needAddress,
      ios: ios
    )
  }
  func toList() -> [Any?] {
    return [
      accuracy,
      intervalMillis,
      timeoutMillis,
      needAddress,
      ios,
    ]
  }
  static func == (lhs: NativeLocationOptions, rhs: NativeLocationOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LocationMessagesPigeonInternal.deepEquals(lhs.accuracy, rhs.accuracy) && LocationMessagesPigeonInternal.deepEquals(lhs.intervalMillis, rhs.intervalMillis) && LocationMessagesPigeonInternal.deepEquals(lhs.timeoutMillis, rhs.timeoutMillis) && LocationMessagesPigeonInternal.deepEquals(lhs.needAddress, rhs.needAddress) && LocationMessagesPigeonInternal.deepEquals(lhs.ios, rhs.ios)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeLocationOptions")
    LocationMessagesPigeonInternal.deepHash(value: accuracy, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: intervalMillis, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: timeoutMillis, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: needAddress, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: ios, hasher: &hasher)
  }

  public var description: String {
    return "NativeLocationOptions(accuracy: \(String(describing: accuracy)), intervalMillis: \(String(describing: intervalMillis)), timeoutMillis: \(String(describing: timeoutMillis)), needAddress: \(String(describing: needAddress)), ios: \(String(describing: ios)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeIosLocationOptions: Hashable, CustomStringConvertible {
  var desiredAccuracy: NativeIosDesiredAccuracy? = nil
  var distanceFilterMeters: Double? = nil
  var pausesLocationUpdatesAutomatically: Bool
  var locationAccuracyMode: NativeIosAccuracyMode? = nil
  var fullAccuracyPurposeKey: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeIosLocationOptions? {
    let desiredAccuracy: NativeIosDesiredAccuracy? = nilOrValue(pigeonVar_list[0])
    let distanceFilterMeters: Double? = nilOrValue(pigeonVar_list[1])
    let pausesLocationUpdatesAutomatically = pigeonVar_list[2] as! Bool
    let locationAccuracyMode: NativeIosAccuracyMode? = nilOrValue(pigeonVar_list[3])
    let fullAccuracyPurposeKey: String? = nilOrValue(pigeonVar_list[4])

    return NativeIosLocationOptions(
      desiredAccuracy: desiredAccuracy,
      distanceFilterMeters: distanceFilterMeters,
      pausesLocationUpdatesAutomatically: pausesLocationUpdatesAutomatically,
      locationAccuracyMode: locationAccuracyMode,
      fullAccuracyPurposeKey: fullAccuracyPurposeKey
    )
  }
  func toList() -> [Any?] {
    return [
      desiredAccuracy,
      distanceFilterMeters,
      pausesLocationUpdatesAutomatically,
      locationAccuracyMode,
      fullAccuracyPurposeKey,
    ]
  }
  static func == (lhs: NativeIosLocationOptions, rhs: NativeIosLocationOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LocationMessagesPigeonInternal.deepEquals(lhs.desiredAccuracy, rhs.desiredAccuracy) && LocationMessagesPigeonInternal.deepEquals(lhs.distanceFilterMeters, rhs.distanceFilterMeters) && LocationMessagesPigeonInternal.deepEquals(lhs.pausesLocationUpdatesAutomatically, rhs.pausesLocationUpdatesAutomatically) && LocationMessagesPigeonInternal.deepEquals(lhs.locationAccuracyMode, rhs.locationAccuracyMode) && LocationMessagesPigeonInternal.deepEquals(lhs.fullAccuracyPurposeKey, rhs.fullAccuracyPurposeKey)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeIosLocationOptions")
    LocationMessagesPigeonInternal.deepHash(value: desiredAccuracy, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: distanceFilterMeters, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: pausesLocationUpdatesAutomatically, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: locationAccuracyMode, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: fullAccuracyPurposeKey, hasher: &hasher)
  }

  public var description: String {
    return "NativeIosLocationOptions(desiredAccuracy: \(String(describing: desiredAccuracy)), distanceFilterMeters: \(String(describing: distanceFilterMeters)), pausesLocationUpdatesAutomatically: \(String(describing: pausesLocationUpdatesAutomatically)), locationAccuracyMode: \(String(describing: locationAccuracyMode)), fullAccuracyPurposeKey: \(String(describing: fullAccuracyPurposeKey)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeLocation: Hashable, CustomStringConvertible {
  var latitude: Double
  var longitude: Double
  var accuracyMeters: Double
  var timestampMillis: Int64
  var coordinateType: NativeCoordinateType
  var address: NativeLocationAddress? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeLocation? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double
    let accuracyMeters = pigeonVar_list[2] as! Double
    let timestampMillis = pigeonVar_list[3] as! Int64
    let coordinateType = pigeonVar_list[4] as! NativeCoordinateType
    let address: NativeLocationAddress? = nilOrValue(pigeonVar_list[5])

    return NativeLocation(
      latitude: latitude,
      longitude: longitude,
      accuracyMeters: accuracyMeters,
      timestampMillis: timestampMillis,
      coordinateType: coordinateType,
      address: address
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
      accuracyMeters,
      timestampMillis,
      coordinateType,
      address,
    ]
  }
  static func == (lhs: NativeLocation, rhs: NativeLocation) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LocationMessagesPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && LocationMessagesPigeonInternal.deepEquals(lhs.longitude, rhs.longitude) && LocationMessagesPigeonInternal.deepEquals(lhs.accuracyMeters, rhs.accuracyMeters) && LocationMessagesPigeonInternal.deepEquals(lhs.timestampMillis, rhs.timestampMillis) && LocationMessagesPigeonInternal.deepEquals(lhs.coordinateType, rhs.coordinateType) && LocationMessagesPigeonInternal.deepEquals(lhs.address, rhs.address)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeLocation")
    LocationMessagesPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: longitude, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: accuracyMeters, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: timestampMillis, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: coordinateType, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: address, hasher: &hasher)
  }

  public var description: String {
    return "NativeLocation(latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)), accuracyMeters: \(String(describing: accuracyMeters)), timestampMillis: \(String(describing: timestampMillis)), coordinateType: \(String(describing: coordinateType)), address: \(String(describing: address)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeLocationAddress: Hashable, CustomStringConvertible {
  var formattedAddress: String? = nil
  var country: String? = nil
  var province: String? = nil
  var city: String? = nil
  var district: String? = nil
  var cityCode: String? = nil
  var adCode: String? = nil
  var street: String? = nil
  var streetNumber: String? = nil
  var poiName: String? = nil
  var aoiName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeLocationAddress? {
    let formattedAddress: String? = nilOrValue(pigeonVar_list[0])
    let country: String? = nilOrValue(pigeonVar_list[1])
    let province: String? = nilOrValue(pigeonVar_list[2])
    let city: String? = nilOrValue(pigeonVar_list[3])
    let district: String? = nilOrValue(pigeonVar_list[4])
    let cityCode: String? = nilOrValue(pigeonVar_list[5])
    let adCode: String? = nilOrValue(pigeonVar_list[6])
    let street: String? = nilOrValue(pigeonVar_list[7])
    let streetNumber: String? = nilOrValue(pigeonVar_list[8])
    let poiName: String? = nilOrValue(pigeonVar_list[9])
    let aoiName: String? = nilOrValue(pigeonVar_list[10])

    return NativeLocationAddress(
      formattedAddress: formattedAddress,
      country: country,
      province: province,
      city: city,
      district: district,
      cityCode: cityCode,
      adCode: adCode,
      street: street,
      streetNumber: streetNumber,
      poiName: poiName,
      aoiName: aoiName
    )
  }
  func toList() -> [Any?] {
    return [
      formattedAddress,
      country,
      province,
      city,
      district,
      cityCode,
      adCode,
      street,
      streetNumber,
      poiName,
      aoiName,
    ]
  }
  static func == (lhs: NativeLocationAddress, rhs: NativeLocationAddress) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LocationMessagesPigeonInternal.deepEquals(lhs.formattedAddress, rhs.formattedAddress) && LocationMessagesPigeonInternal.deepEquals(lhs.country, rhs.country) && LocationMessagesPigeonInternal.deepEquals(lhs.province, rhs.province) && LocationMessagesPigeonInternal.deepEquals(lhs.city, rhs.city) && LocationMessagesPigeonInternal.deepEquals(lhs.district, rhs.district) && LocationMessagesPigeonInternal.deepEquals(lhs.cityCode, rhs.cityCode) && LocationMessagesPigeonInternal.deepEquals(lhs.adCode, rhs.adCode) && LocationMessagesPigeonInternal.deepEquals(lhs.street, rhs.street) && LocationMessagesPigeonInternal.deepEquals(lhs.streetNumber, rhs.streetNumber) && LocationMessagesPigeonInternal.deepEquals(lhs.poiName, rhs.poiName) && LocationMessagesPigeonInternal.deepEquals(lhs.aoiName, rhs.aoiName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeLocationAddress")
    LocationMessagesPigeonInternal.deepHash(value: formattedAddress, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: country, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: province, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: city, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: district, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: cityCode, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: adCode, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: street, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: streetNumber, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: poiName, hasher: &hasher)
    LocationMessagesPigeonInternal.deepHash(value: aoiName, hasher: &hasher)
  }

  public var description: String {
    return "NativeLocationAddress(formattedAddress: \(String(describing: formattedAddress)), country: \(String(describing: country)), province: \(String(describing: province)), city: \(String(describing: city)), district: \(String(describing: district)), cityCode: \(String(describing: cityCode)), adCode: \(String(describing: adCode)), street: \(String(describing: street)), streetNumber: \(String(describing: streetNumber)), poiName: \(String(describing: poiName)), aoiName: \(String(describing: aoiName)))"
  }
}

private class LocationMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeLocationAccuracy(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeIosDesiredAccuracy(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeIosAccuracyMode(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeCoordinateType(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeLocationErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      return NativePrivacyStatus.fromList(self.readValue() as! [Any?])
    case 135:
      return NativeLocationOptions.fromList(self.readValue() as! [Any?])
    case 136:
      return NativeIosLocationOptions.fromList(self.readValue() as! [Any?])
    case 137:
      return NativeLocation.fromList(self.readValue() as! [Any?])
    case 138:
      return NativeLocationAddress.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LocationMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeLocationAccuracy {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeIosDesiredAccuracy {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeIosAccuracyMode {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeCoordinateType {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeLocationErrorCode {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativePrivacyStatus {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? NativeLocationOptions {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? NativeIosLocationOptions {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? NativeLocation {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? NativeLocationAddress {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LocationMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LocationMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LocationMessagesPigeonCodecWriter(data: data)
  }
}

class LocationMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LocationMessagesPigeonCodec(readerWriter: LocationMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LocationHostApi {
  func setApiKey(apiKey: String) throws
  func setPrivacyStatus(status: NativePrivacyStatus) throws
  func isLocationServiceEnabled() throws -> Bool
  func createClient(options: NativeLocationOptions) throws -> Int64
  func setLocationOption(clientId: Int64, options: NativeLocationOptions) throws
  func getCurrentLocation(clientId: Int64, completion: @escaping (Result<NativeLocation, Error>) -> Void)
  func start(clientId: Int64) throws
  func stop(clientId: Int64) throws
  func disposeClient(clientId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LocationHostApiSetup {
  static var codec: FlutterStandardMessageCodec { LocationMessagesPigeonCodec.shared }
  /// Sets up an instance of `LocationHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LocationHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setApiKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_kit_location_ios.LocationHostApi.setApiKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setApiKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let apiKeyArg = args[0] as! String
        do {
          try api.setApiKey(apiKey: apiKeyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setApiKeyChannel.setMessageHandler(nil)
    }
    let setPrivacyStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_kit_location_ios.LocationHostApi.setPrivacyStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPrivacyStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let statusArg = args[0] as! NativePrivacyStatus
        do {
          try api.setPrivacyStatus(status: statusArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPrivacyStatusChannel.setMessageHandler(nil)
    }
    let isLocationServiceEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_kit_location_ios.LocationHostApi.isLocationServiceEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isLocationServiceEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isLocationServiceEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isLocationServiceEnabledChannel.setMessageHandler(nil)
    }
    let createClientChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_kit_location_ios.LocationHostApi.createClient\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createClientChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! NativeLocationOptions
        do {
          let result = try api.createClient(options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createClientChannel.setMessageHandler(nil)
    }
    let setLocationOptionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_kit_location_ios.LocationHostApi.setLocationOption\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLocationOptionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        let optionsArg = args[1] as! NativeLocationOptions
        do {
          try api.setLocationOption(clientId: clientIdArg, options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLocationOptionChannel.setMessageHandler(nil)
    }
    let getCurrentLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_kit_location_ios.LocationHostApi.getCurrentLocation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCurrentLocationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        api.getCurrentLocation(clientId: clientIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCurrentLocationChannel.setMessageHandler(nil)
    }
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_kit_location_ios.LocationHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        do {
          try api.start(clientId: clientIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_kit_location_ios.LocationHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        do {
          try api.stop(clientId: clientIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let disposeClientChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.amap_kit_location_ios.LocationHostApi.disposeClient\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeClientChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! Int64
        do {
          try api.disposeClient(clientId: clientIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeClientChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LocationFlutterApiProtocol {
  func onLocation(clientId clientIdArg: Int64, location locationArg: NativeLocation, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(clientId clientIdArg: Int64, code codeArg: NativeLocationErrorCode, message messageArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class LocationFlutterApi: LocationFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: LocationMessagesPigeonCodec {
    return LocationMessagesPigeonCodec.shared
  }
  func onLocation(clientId clientIdArg: Int64, location locationArg: NativeLocation, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.amap_kit_location_ios.LocationFlutterApi.onLocation\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([clientIdArg, locationArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onError(clientId clientIdArg: Int64, code codeArg: NativeLocationErrorCode, message messageArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.amap_kit_location_ios.LocationFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([clientIdArg, codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
