name: amap_kit_map_android
description: Android implementation for amap_kit_map.
version: 0.1.0
repository: https://github.com/ryujane/amap_kit

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

resolution: workspace

dependencies:
  amap_kit_core: ^0.1.0
  amap_kit_map_platform_interface: ^0.1.0
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.35
  meta: ^1.16.0
  stream_transform: ^2.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  pigeon: ^27.3.0

flutter:
  plugin:
    implements: amap_kit_map
    platforms:
      android:
        package: com.github.amapkit.map
        pluginClass: AmapMapNativePlugin
        dartPluginClass: AmapMapsFlutterAndroid
